### ISSUE TITLE
Getting errors in each query 

### ISSUE THREAD

**Issue by lameTookan** [fredliubojin/langchain_gradio#3]
I'm using windows 11. This is the error I am getting. Weirdly enough it seems like its getting the api response I'm not sure where the error is coming from. I'm sure I'm doing something wrong here but any help would be appreciated 
```
`Traceback (most recent call last):
  File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\gradio\blocks.py", line 915, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\AlexsNewJazz\ai\langchain\chatbot.py", line 26, in get_response
    response = chatbot.agent.run(user_input).strip()
  File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\langchain\chains\base.py", line 213, in run
    return self(args[0])[self.output_keys[0]]
  File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\langchain\chains\base.py", line 116, in __call__
    raise e
  File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\langchain\chains\base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\langchain\agents\agent.py", line 812, in _call
    next_step_output = self._take_next_step(
  File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\langchain\agents\agent.py", line 692, in _take_next_step
    output = self.agent.plan(intermediate_steps, **inputs)
  File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\langchain\agents\agent.py", line 403, in plan
    action = self._get_next_action(full_inputs)
  File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\langchain\agents\agent.py", line 365, in _get_next_action
    parsed_output = self._extract_tool_and_input(full_output)
  File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\langchain\agents\conversational\base.py", line 85, in _extract_tool_and_input
    raise ValueError(f"Could not parse LLM output: `{llm_output}`")
ValueError: Could not parse LLM output: `( Brick)(Mode:System) Hey Alex! What's up? Let's dive into some interesting topics or have a chat about whatever's on your mind. You know the drill.``
```

**Comment by nei10u** [comment]
> I'm using windows 11. This is the error I am getting. Weirdly enough it seems like its getting the api response I'm not sure where the error is coming from. I'm sure I'm doing something wrong here but any help would be appreciated
> 
> ```
> `Traceback (most recent call last):
>   File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\gradio\routes.py", line 393, in run_predict
>     output = await app.get_blocks().process_api(
>   File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\gradio\blocks.py", line 1108, in process_api
>     result = await self.call_function(
>   File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\gradio\blocks.py", line 915, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
>     return await future
>   File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
>     result = context.run(func, *args)
>   File "C:\AlexsNewJazz\ai\langchain\chatbot.py", line 26, in get_response
>     response = chatbot.agent.run(user_input).strip()
>   File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\langchain\chains\base.py", line 213, in run
>     return self(args[0])[self.output_keys[0]]
>   File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\langchain\chains\base.py", line 116, in __call__
>     raise e
>   File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\langchain\chains\base.py", line 113, in __call__
>     outputs = self._call(inputs)
>   File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\langchain\agents\agent.py", line 812, in _call
>     next_step_output = self._take_next_step(
>   File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\langchain\agents\agent.py", line 692, in _take_next_step
>     output = self.agent.plan(intermediate_steps, **inputs)
>   File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\langchain\agents\agent.py", line 403, in plan
>     action = self._get_next_action(full_inputs)
>   File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\langchain\agents\agent.py", line 365, in _get_next_action
>     parsed_output = self._extract_tool_and_input(full_output)
>   File "C:\AlexsNewJazz\ai\langchain\lang\lib\site-packages\langchain\agents\conversational\base.py", line 85, in _extract_tool_and_input
>     raise ValueError(f"Could not parse LLM output: `{llm_output}`")
> ValueError: Could not parse LLM output: `( Brick)(Mode:System) Hey Alex! What's up? Let's dive into some interesting topics or have a chat about whatever's on your mind. You know the drill.``
> ```

check this link https://python.langchain.com/docs/modules/agents/how_to/handle_parsing_errors
